### ISSUE TITLE
Fatal config file error

### ISSUE THREAD

**Issue by killmasta93** [RedisLabsModules/redis-timeseries#9]
Hi,
I was wondering if someone has had the same issue has trying to import the module i keep getting 

root@sqlserver:~/redis-timeseries/src# redis-server --loadmodule /root/redis-timeseries/src/redis-tsdb-module.so

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'loadmodule "/root/redis-timeseries/src/redis-tsdb-module.so"'
Bad directive or wrong number of arguments

any ideas?

**Comment by itamarhaber** [comment]
Hello @killmasta93 

Most likely, your redis-server version is too low. Modules are supported in Redis v4 or above.

Closing this issue - feel free to reopen.
